* Funzionamento
Per octave, una alternativa GNU a Matlab non é possibile misurare la
memoria utilizzata.  Allora é possibile usare il comando qui sotto (se
su Linux, forse va anche su Windows installando Cygwin o simili) per
misurare la massima (peak) memoria utilizzata dal processo in
KB. Volendo si puó vedere la memoria media utilizzata con il
aggiungendo a -f "%K".

Il comando é generico, va bene per qualsiasi processo, lo potremmo
utilizzare anche per altre librerie.  Matlab su windows ha la funzione
memory che fa questa cosa in automatico, su linux invece non va,
potremmo usare il comando qui sotto in quel caso.

#+begin_src bash
  /usr/bin/time -f "%M" nome-processo
#+end_src

Da notare che il comando

#+begin_src bash
  /usr/bin/time
#+end_src

non é lo stesso comando che fare:
#+begin_src bash
  time
#+end_src

Lo [[file:analisi-octave.sh][Script bash per automatizzare]] in pratica salva in due file diversi
i risultati di utilizzo della memoria e di statistiche misurabili da
dentro octave (dimensione matrice, errore relativo, tempo impiegato).
I due file alla fine vengono messi insieme nel file risultati.txt.

Il file octave che si occupa di fare i calcoli é [[file:octave-test.m][questo.]]

Alla fine risultati.txt é un file csv separato da ";", l'ordine di
elementi é :

1. Dimensione matrice (nrighe*ncolonne)
2. Errore relativo
3. Tempo impiegato
4. Memoria massima utilizzata (in KB)

Per ogni invocazione dello script bash bisogna cancellare a mano i
file creati alla invocazione precedente, non metto il codice per
eliminarli automaticamente per evitare di sbagliare e cancellare per
errore altri file/cartelle.

Passo per file intermedi perché in Bash é un casino ottenere il valore
di ritorno di una funzione in una variabile, allora scrivo il
risultato in un file e poi me lo gestisco.

Poi con questi dati possiamo fare i grafici con un qualche programma.

* Todo
Le matrici bundle_ adj, ifiss non sono in un formato standard, lo
script [[file:conversione-matrici.m][conversione-matrici.m]] serve a trasformarli in un formato
standard utilizzabile dallo script [[file:octave-test.m][octave-test.m]].

Questo é il ragionamento seguito per la conversione [[https://stackoverflow.com/questions/67297942/how-to-convert-a-matrix-saved-as-a-struct-to-matrix/67301837#67301837][link stackoverflow]].

Una volta fatta la conversione di queste matrici vanno sostituite alle
matrici originali.

La matrice Hook da segmentation fault (out of memory), probabilmente
perché ho solo 8gb di ram.

* Per windows
Su windows é possibile installare [[https://www.cygwin.com/][Cygwin]] per usare comandi linux,
durante il processo di installazione viene chiesto quali pacchetti
installare. Nella sezione 'Math' va aggiunto octave, nella sezione
'Utilities' va aggiunto il comando time.

La versione di octave offerta da cygwin é la 5.2, quindi su linux ha
senso utilizzare la stessa versione. (La versione piú recente é la 6).
Dal [[https://www.gnu.org/software/octave/news/release/2021/02/20/octave-6.2.0-released.html][changelog]] della 6 di octave non sembra essere cambiato niente che
noi utilizziamo.
